questions = [
{
    content: "穴熊に関するクイズ問題その1。この局面で最善手は？",
    image_path: "db/seed_images/穴熊１.png",
    pattern: "穴熊",
    option1_path: "db/seed_images/穴熊１成功１.png",
    option2_path: "db/seed_images/穴熊１失敗１.png",
    correct: 1,
    e_imagesippai1_path: "db/seed_images/穴熊１失敗１.png",
    e_imagesippai2_path: "db/seed_images/穴熊１失敗２.png",
    e_imagesippai3_path: "db/seed_images/穴熊１失敗３.png",
    e_imagesippai4_path: "db/seed_images/穴熊１失敗４.png",
    e_imageseiko1_path: "db/seed_images/穴熊１成功１.png",
    e_imageseiko2_path: "db/seed_images/穴熊１成功２.png",
    e_imageseiko3_path: "db/seed_images/穴熊１成功３.png",
    e_imageseiko4_path: "db/seed_images/穴熊１成功４.png",
    e_imageseiko5_path: "db/seed_images/穴熊１成功５.png",
    e_imageseiko6_path: "db/seed_images/穴熊１成功６.png",
    e_imageseiko7_path: "db/seed_images/穴熊１成功７.png"
  },
  {
    content: "穴熊に関するクイズ問題その2。この局面で最善手は？",
    image_path: "db/seed_images/穴熊２.png",
    pattern: "穴熊",
    option1_path: "db/seed_images/穴熊２失敗１.png",
    option2_path: "db/seed_images/穴熊２成功１.png",
    correct: 2,
    e_imagesippai1_path: "db/seed_images/穴熊２失敗１.png",
    e_imagesippai2_path: "db/seed_images/穴熊２失敗２.png",
    e_imagesippai3_path: "db/seed_images/穴熊２失敗３.png",
    e_imagesippai4_path: "db/seed_images/穴熊２失敗４.png",
    e_imagesippai5_path: "db/seed_images/穴熊２失敗５.png",
    e_imagesippai6_path: "db/seed_images/穴熊２失敗６.png",
    e_imagesippai7_path: "db/seed_images/穴熊２失敗７.png",
    e_imagesippai8_path: "db/seed_images/穴熊２失敗８.png",
    e_imagesippai9_path: "db/seed_images/穴熊２失敗９.png",
    e_imagesippai10_path: "db/seed_images/穴熊２失敗１０.png",
    e_imageseiko1_path: "db/seed_images/穴熊２成功１.png",
    e_imageseiko2_path: "db/seed_images/穴熊２成功２.png",
    e_imageseiko3_path: "db/seed_images/穴熊２成功３.png",
    e_imageseiko4_path: "db/seed_images/穴熊２成功４.png",
    e_imageseiko5_path: "db/seed_images/穴熊２成功５.png"
  },
  {
    content: "穴熊に関するクイズ問題その3。この局面で最善手は？",
    image_path: "db/seed_images/穴熊３.png",
    pattern: "穴熊",
    option1_path: "db/seed_images/穴熊３成功１.png",
    option2_path: "db/seed_images/穴熊３失敗１.png",
    correct: 1,
    e_imagesippai1_path: "db/seed_images/穴熊３失敗１.png",
    e_imagesippai2_path: "db/seed_images/穴熊３失敗２.png",
    e_imagesippai3_path: "db/seed_images/穴熊３失敗３.png",
    e_imagesippai4_path: "db/seed_images/穴熊３失敗４.png",
    e_imagesippai5_path: "db/seed_images/穴熊３失敗５.png",
    e_imageseiko1_path: "db/seed_images/穴熊３成功１.png",
    e_imageseiko2_path: "db/seed_images/穴熊３成功２.png",
    e_imageseiko3_path: "db/seed_images/穴熊３成功３.png",
    e_imageseiko4_path: "db/seed_images/穴熊３成功４.png",
    e_imageseiko5_path: "db/seed_images/穴熊３成功５.png",
    e_imageseiko6_path: "db/seed_images/穴熊３成功６.png",
    e_imageseiko7_path: "db/seed_images/穴熊３成功７.png",
    e_imageseiko8_path: "db/seed_images/穴熊３成功８.png",
    e_imageseiko9_path: "db/seed_images/穴熊３成功９.png"
  },
  {
    content: "穴熊に関するクイズ問題その4。この局面で最善手は？",
    image_path: "db/seed_images/穴熊４.png",
    pattern: "穴熊",
    option1_path: "db/seed_images/穴熊４失敗１.png",
    option2_path: "db/seed_images/穴熊４成功１.png",
    correct: 2,
    e_imagesippai1_path: "db/seed_images/穴熊４失敗１.png",
    e_imagesippai2_path: "db/seed_images/穴熊４失敗２.png",
    e_imagesippai3_path: "db/seed_images/穴熊４失敗３.png",
    e_imagesippai4_path: "db/seed_images/穴熊４失敗４.png",
    e_imagesippai5_path: "db/seed_images/穴熊４失敗５.png",
    e_imagesippai6_path: "db/seed_images/穴熊４失敗６.png",
    e_imagesippai7_path: "db/seed_images/穴熊４失敗７.png",
    e_imagesippai8_path: "db/seed_images/穴熊４失敗８.png",
    e_imagesippai9_path: "db/seed_images/穴熊４失敗９.png",
    e_imagesippai10_path: "db/seed_images/穴熊４失敗１０.png",
    e_imageseiko1_path: "db/seed_images/穴熊４成功１.png",
    e_imageseiko2_path: "db/seed_images/穴熊４成功２.png",
    e_imageseiko3_path: "db/seed_images/穴熊４成功３.png",
    e_imageseiko4_path: "db/seed_images/穴熊４成功４.png",
    e_imageseiko5_path: "db/seed_images/穴熊４成功５.png",
    e_imageseiko6_path: "db/seed_images/穴熊４成功６.png",
    e_imageseiko7_path: "db/seed_images/穴熊４成功７.png",
    e_imageseiko8_path: "db/seed_images/穴熊４成功８.png",
    e_imageseiko9_path: "db/seed_images/穴熊４成功９.png"
  },
  {
    content: "穴熊に関するクイズ問題その5。この局面で最善手は？",
    image_path: "db/seed_images/穴熊５.png",
    pattern: "穴熊",
    option1_path: "db/seed_images/穴熊５成功１.png",
    option2_path: "db/seed_images/穴熊５失敗１.png",
    correct: 1,
    e_imagesippai1_path: "db/seed_images/穴熊５失敗１.png",
    e_imagesippai2_path: "db/seed_images/穴熊５失敗２.png",
    e_imagesippai3_path: "db/seed_images/穴熊５失敗３.png",
    e_imagesippai4_path: "db/seed_images/穴熊５失敗４.png",
    e_imagesippai5_path: "db/seed_images/穴熊５失敗５.png",
    e_imagesippai6_path: "db/seed_images/穴熊５失敗６.png",
    e_imagesippai7_path: "db/seed_images/穴熊５失敗７.png",
    e_imagesippai8_path: "db/seed_images/穴熊５失敗８.png",
    e_imagesippai9_path: "db/seed_images/穴熊５失敗９.png",
    e_imagesippai10_path: "db/seed_images/穴熊５失敗１０.png",
    e_imagesippai11_path: "db/seed_images/穴熊５失敗１１.png",
    e_imagesippai12_path: "db/seed_images/穴熊５失敗１２.png",
    e_imagesippai13_path: "db/seed_images/穴熊５失敗１３.png",
    e_imagesippai14_path: "db/seed_images/穴熊５失敗１４.png",
    e_imagesippai15_path: "db/seed_images/穴熊５失敗１５.png",
    e_imagesippai16_path: "db/seed_images/穴熊５失敗１６.png",
    e_imageseiko1_path: "db/seed_images/穴熊５成功１.png",
    e_imageseiko2_path: "db/seed_images/穴熊５成功２.png",
    e_imageseiko3_path: "db/seed_images/穴熊５成功３.png",
    e_imageseiko4_path: "db/seed_images/穴熊５成功４.png",
    e_imageseiko5_path: "db/seed_images/穴熊５成功５.png",
    e_imageseiko6_path: "db/seed_images/穴熊５成功６.png",
    e_imageseiko7_path: "db/seed_images/穴熊５成功７.png",
    e_imageseiko8_path: "db/seed_images/穴熊５成功８.png",
    e_imageseiko9_path: "db/seed_images/穴熊５成功９.png"
  },
  {
    content: "穴熊に関するクイズ問題その6。この局面で最善手は？",
    image_path: "db/seed_images/穴熊６.png",
    pattern: "穴熊",
    option1_path: "db/seed_images/穴熊６失敗１.png",
    option2_path: "db/seed_images/穴熊６成功１.png",
    correct: 2,
    e_imagesippai1_path: "db/seed_images/穴熊６失敗１.png",
    e_imagesippai2_path: "db/seed_images/穴熊６失敗２.png",
    e_imagesippai3_path: "db/seed_images/穴熊６失敗３.png",
    e_imagesippai4_path: "db/seed_images/穴熊６失敗４.png",
    e_imagesippai5_path: "db/seed_images/穴熊６失敗５.png",
    e_imagesippai6_path: "db/seed_images/穴熊６失敗６.png",
    e_imagesippai7_path: "db/seed_images/穴熊６失敗７.png",
    e_imagesippai8_path: "db/seed_images/穴熊６失敗８.png",
    e_imageseiko1_path: "db/seed_images/穴熊６成功１.png",
    e_imageseiko2_path: "db/seed_images/穴熊６成功２.png",
    e_imageseiko3_path: "db/seed_images/穴熊６成功３.png",
    e_imageseiko4_path: "db/seed_images/穴熊６成功４.png",
    e_imageseiko5_path: "db/seed_images/穴熊６成功５.png",
    e_imageseiko6_path: "db/seed_images/穴熊６成功６.png",
    e_imageseiko7_path: "db/seed_images/穴熊６成功７.png",
    e_imageseiko8_path: "db/seed_images/穴熊６成功８.png",
    e_imageseiko9_path: "db/seed_images/穴熊６成功９.png",
    e_imageseiko10_path: "db/seed_images/穴熊６成功１０.png",
    e_imageseiko11_path: "db/seed_images/穴熊６成功１１.png",
    e_imageseiko12_path: "db/seed_images/穴熊６成功１２.png",
    e_imageseiko13_path: "db/seed_images/穴熊６成功１３.png",
    e_imageseiko14_path: "db/seed_images/穴熊６成功１４.png",
    e_imageseiko15_path: "db/seed_images/穴熊６成功１５.png"
  },
  {
    content: "穴熊に関するクイズ問題その7。この局面で最善手は？",
    image_path: "db/seed_images/穴熊７.png",
    pattern: "穴熊",
    option1_path: "db/seed_images/穴熊７成功１.png",
    option2_path: "db/seed_images/穴熊７失敗１.png",
    correct: 1,
    e_imagesippai1_path: "db/seed_images/穴熊７失敗１.png",
    e_imagesippai2_path: "db/seed_images/穴熊７失敗２.png",
    e_imagesippai3_path: "db/seed_images/穴熊７失敗３.png",
    e_imagesippai4_path: "db/seed_images/穴熊７失敗４.png",
    e_imagesippai5_path: "db/seed_images/穴熊７失敗５.png",
    e_imagesippai6_path: "db/seed_images/穴熊７失敗６.png",
    e_imagesippai7_path: "db/seed_images/穴熊７失敗７.png",
    e_imagesippai8_path: "db/seed_images/穴熊７失敗８.png",
    e_imagesippai9_path: "db/seed_images/穴熊７失敗９.png",
    e_imagesippai10_path: "db/seed_images/穴熊７失敗１０.png",
    e_imagesippai11_path: "db/seed_images/穴熊７失敗１１.png",
    e_imagesippai12_path: "db/seed_images/穴熊７失敗１２.png",
    e_imagesippai13_path: "db/seed_images/穴熊７失敗１３.png",
    e_imagesippai14_path: "db/seed_images/穴熊７失敗１４.png",
    e_imagesippai15_path: "db/seed_images/穴熊７失敗１５.png",
    e_imagesippai16_path: "db/seed_images/穴熊７失敗１６.png",
    e_imagesippai17_path: "db/seed_images/穴熊７失敗１７.png",
    e_imagesippai18_path: "db/seed_images/穴熊７失敗１８.png",
    e_imageseiko1_path: "db/seed_images/穴熊７成功１.png",
    e_imageseiko2_path: "db/seed_images/穴熊７成功２.png",
    e_imageseiko3_path: "db/seed_images/穴熊７成功３.png",
    e_imageseiko4_path: "db/seed_images/穴熊７成功４.png",
    e_imageseiko5_path: "db/seed_images/穴熊７成功５.png",
    e_imageseiko6_path: "db/seed_images/穴熊７成功６.png",
    e_imageseiko7_path: "db/seed_images/穴熊７成功７.png",
    e_imageseiko8_path: "db/seed_images/穴熊７成功８.png",
    e_imageseiko9_path: "db/seed_images/穴熊７成功９.png",
    e_imageseiko10_path: "db/seed_images/穴熊７成功１０.png",
    e_imageseiko11_path: "db/seed_images/穴熊７成功１１.png"
  },
  {
    content: "穴熊に関するクイズ問題その8。この局面で最善手は？",
    image_path: "db/seed_images/穴熊８.png",
    pattern: "穴熊",
    option1_path: "db/seed_images/穴熊８失敗１.png",
    option2_path: "db/seed_images/穴熊８成功１.png",
    correct: 2,
    e_imagesippai1_path: "db/seed_images/穴熊８失敗１.png",
    e_imagesippai2_path: "db/seed_images/穴熊８失敗２.png",
    e_imagesippai3_path: "db/seed_images/穴熊８失敗３.png",
    e_imagesippai4_path: "db/seed_images/穴熊８失敗４.png",
    e_imagesippai5_path: "db/seed_images/穴熊８失敗５.png",
    e_imagesippai6_path: "db/seed_images/穴熊８失敗６.png",
    e_imageseiko1_path: "db/seed_images/穴熊８成功１.png",
    e_imageseiko2_path: "db/seed_images/穴熊８成功２.png",
    e_imageseiko3_path: "db/seed_images/穴熊８成功３.png",
    e_imageseiko4_path: "db/seed_images/穴熊８成功４.png",
    e_imageseiko5_path: "db/seed_images/穴熊８成功５.png",
    e_imageseiko6_path: "db/seed_images/穴熊８成功６.png"
  },
  {
    content: "穴熊に関するクイズ問題その9。この局面で最善手は？",
    image_path: "db/seed_images/穴熊９.png",
    pattern: "穴熊",
    option1_path: "db/seed_images/穴熊９成功１.png",
    option2_path: "db/seed_images/穴熊９失敗１.png",
    correct: 1,
    e_imagesippai1_path: "db/seed_images/穴熊９失敗１.png",
    e_imagesippai2_path: "db/seed_images/穴熊９失敗２.png",
    e_imagesippai3_path: "db/seed_images/穴熊９失敗３.png",
    e_imagesippai4_path: "db/seed_images/穴熊９失敗４.png",
    e_imagesippai5_path: "db/seed_images/穴熊９失敗５.png",
    e_imagesippai6_path: "db/seed_images/穴熊９失敗６.png",
    e_imagesippai7_path: "db/seed_images/穴熊９失敗７.png",
    e_imagesippai8_path: "db/seed_images/穴熊９失敗８.png",
    e_imagesippai9_path: "db/seed_images/穴熊９失敗９.png",
    e_imagesippai10_path: "db/seed_images/穴熊９失敗１０.png",
    e_imagesippai11_path: "db/seed_images/穴熊９失敗１１.png",
    e_imagesippai12_path: "db/seed_images/穴熊９失敗１２.png",
    e_imagesippai13_path: "db/seed_images/穴熊９失敗１３.png",
    e_imagesippai14_path: "db/seed_images/穴熊９失敗１４.png",
    e_imagesippai15_path: "db/seed_images/穴熊９失敗１５.png",
    e_imagesippai16_path: "db/seed_images/穴熊９失敗１６.png",
    e_imageseiko1_path: "db/seed_images/穴熊９成功１.png",
    e_imageseiko2_path: "db/seed_images/穴熊９成功２.png",
    e_imageseiko3_path: "db/seed_images/穴熊９成功３.png",
    e_imageseiko4_path: "db/seed_images/穴熊９成功４.png",
    e_imageseiko5_path: "db/seed_images/穴熊９成功５.png"
  },
  {
    content: "穴熊に関するクイズ問題その10。この局面で最善手は？",
    image_path: "db/seed_images/穴熊１０.png",
    pattern: "穴熊",
    option1_path: "db/seed_images/穴熊１０失敗１.png",
    option2_path: "db/seed_images/穴熊１０成功１.png",
    correct: 2,
    e_imagesippai1_path: "db/seed_images/穴熊１０失敗１.png",
    e_imagesippai2_path: "db/seed_images/穴熊１０失敗２.png",
    e_imagesippai3_path: "db/seed_images/穴熊１０失敗３.png",
    e_imagesippai4_path: "db/seed_images/穴熊１０失敗４.png",
    e_imagesippai5_path: "db/seed_images/穴熊１０失敗５.png",
    e_imagesippai6_path: "db/seed_images/穴熊１０失敗６.png",
    e_imagesippai7_path: "db/seed_images/穴熊１０失敗７.png",
    e_imagesippai8_path: "db/seed_images/穴熊１０失敗８.png",
    e_imagesippai9_path: "db/seed_images/穴熊１０失敗９.png",
    e_imagesippai10_path: "db/seed_images/穴熊１０失敗１０.png",
    e_imageseiko1_path: "db/seed_images/穴熊１０成功１.png",
    e_imageseiko2_path: "db/seed_images/穴熊１０成功２.png",
    e_imageseiko3_path: "db/seed_images/穴熊１０成功３.png",
    e_imageseiko4_path: "db/seed_images/穴熊１０成功４.png",
    e_imageseiko5_path: "db/seed_images/穴熊１０成功５.png",
    e_imageseiko6_path: "db/seed_images/穴熊１０成功６.png",
    e_imageseiko7_path: "db/seed_images/穴熊１０成功７.png"
  }
]

questions.each do |q|
  question = Question.create!(
    content: q[:content],
    pattern: q[:pattern],
    correct: q[:correct]
  )
  question.image.attach(
    io: File.open(Rails.root.join(q[:image_path])),
    filename: File.basename(q[:image_path]),
    content_type: "image/png"
  )
  question.option1.attach(
    io: File.open(Rails.root.join(q[:option1_path])),
    filename: File.basename(q[:option1_path]),
    content_type: "image/png"
  )
  question.option2.attach(
    io: File.open(Rails.root.join(q[:option2_path])),
    filename: File.basename(q[:option2_path]),
    content_type: "image/png"
  )

    q.each do |key, path|
    # e_image で始まるキーだけ拾う（例: :e_imagesippai1_path）
    next unless key.to_s.start_with?("e_image")
    next if path.blank?
    # :e_imagesippai1_path → "e_imagesippai1"
    attachment_name = key.to_s.sub(/_path\z/, "")
    # Question モデルの ActiveStorage に attach
    question.public_send(attachment_name).attach(
      io: File.open(Rails.root.join(path)),
      filename: File.basename(path),
      content_type: "image/png"
    )
  end
end
