questions = [
{
    content: "棒銀に関するクイズ問題その1。この局面で最善手は？",
    image_path: "db/seed_images/棒銀１.png",
    pattern: "棒銀",
    option1_path: "db/seed_images/棒銀１成功１.png",
    option2_path: "db/seed_images/棒銀１失敗１.png",
    correct: 1,
    e_imagesippai1_path: "db/seed_images/棒銀１失敗１.png",
    e_imagesippai2_path: "db/seed_images/棒銀１失敗２.png",
    e_imagesippai3_path: "db/seed_images/棒銀１失敗３.png",
    e_imagesippai4_path: "db/seed_images/棒銀１失敗４.png",
    e_imagesippai5_path: "db/seed_images/棒銀１失敗５.png",
    e_imagesippai6_path: "db/seed_images/棒銀１失敗６.png",
    e_imagesippai7_path: "db/seed_images/棒銀１失敗７.png",
    e_imagesippai8_path: "db/seed_images/棒銀１失敗８.png",
    e_imagesippai9_path: "db/seed_images/棒銀１失敗９.png",
    e_imagesippai10_path: "db/seed_images/棒銀１失敗１０.png",
    e_imageseiko1_path: "db/seed_images/棒銀１成功１.png",
    e_imageseiko2_path: "db/seed_images/棒銀１成功２.png",
    e_imageseiko3_path: "db/seed_images/棒銀１成功３.png",
    e_imageseiko4_path: "db/seed_images/棒銀１成功４.png",
    e_imageseiko5_path: "db/seed_images/棒銀１成功５.png",
    e_imageseiko6_path: "db/seed_images/棒銀１成功６.png",
    e_imageseiko7_path: "db/seed_images/棒銀１成功７.png",
    e_imageseiko8_path: "db/seed_images/棒銀１成功８.png",
    e_imageseiko9_path: "db/seed_images/棒銀１成功９.png",
    e_imageseiko10_path: "db/seed_images/棒銀１成功１０.png",
    e_imageseiko11_path: "db/seed_images/棒銀１成功１１.png",
    e_imageseiko12_path: "db/seed_images/棒銀１成功１２.png",
    e_imageseiko13_path: "db/seed_images/棒銀１成功１３.png",
    e_imageseiko14_path: "db/seed_images/棒銀１成功１４.png",
    e_imageseiko15_path: "db/seed_images/棒銀１成功１５.png",
    e_imageseiko16_path: "db/seed_images/棒銀１成功１６.png"
  },
  {
    content: "棒銀に関するクイズ問題その2。この局面で最善手は？",
    image_path: "db/seed_images/棒銀２.png",
    pattern: "棒銀",
    option1_path: "db/seed_images/棒銀２失敗１.png",
    option2_path: "db/seed_images/棒銀２成功１.png",
    correct: 2,
    e_imagesippai1_path: "db/seed_images/棒銀２失敗１.png",
    e_imagesippai2_path: "db/seed_images/棒銀２失敗２.png",
    e_imagesippai3_path: "db/seed_images/棒銀２失敗３.png",
    e_imagesippai4_path: "db/seed_images/棒銀２失敗４.png",
    e_imagesippai5_path: "db/seed_images/棒銀２失敗５.png",
    e_imagesippai6_path: "db/seed_images/棒銀２失敗６.png",
    e_imageseiko1_path: "db/seed_images/棒銀２成功１.png",
    e_imageseiko2_path: "db/seed_images/棒銀２成功２.png",
    e_imageseiko3_path: "db/seed_images/棒銀２成功３.png",
    e_imageseiko4_path: "db/seed_images/棒銀２成功４.png",
    e_imageseiko5_path: "db/seed_images/棒銀２成功５.png",
    e_imageseiko6_path: "db/seed_images/棒銀２成功６.png",
    e_imageseiko7_path: "db/seed_images/棒銀２成功７.png",
    e_imageseiko8_path: "db/seed_images/棒銀２成功８.png",
    e_imageseiko9_path: "db/seed_images/棒銀２成功９.png"
  },
  {
    content: "棒銀に関するクイズ問題その3。この局面で最善手は？",
    image_path: "db/seed_images/棒銀３.png",
    pattern: "棒銀",
    option1_path: "db/seed_images/棒銀３成功１.png",
    option2_path: "db/seed_images/棒銀３失敗１.png",
    correct: 1,
    e_imagesippai1_path: "db/seed_images/棒銀３失敗１.png",
    e_imagesippai2_path: "db/seed_images/棒銀３失敗２.png",
    e_imagesippai3_path: "db/seed_images/棒銀３失敗３.png",
    e_imagesippai4_path: "db/seed_images/棒銀３失敗４.png",
    e_imagesippai5_path: "db/seed_images/棒銀３失敗５.png",
    e_imagesippai6_path: "db/seed_images/棒銀３失敗６.png",
    e_imagesippai7_path: "db/seed_images/棒銀３失敗７.png",
    e_imagesippai8_path: "db/seed_images/棒銀３失敗８.png",
    e_imagesippai9_path: "db/seed_images/棒銀３失敗９.png",
    e_imagesippai10_path: "db/seed_images/棒銀３失敗１０.png",
    e_imageseiko1_path: "db/seed_images/棒銀３成功１.png",
    e_imageseiko2_path: "db/seed_images/棒銀３成功２.png",
    e_imageseiko3_path: "db/seed_images/棒銀３成功３.png",
    e_imageseiko4_path: "db/seed_images/棒銀３成功４.png",
    e_imageseiko5_path: "db/seed_images/棒銀３成功５.png",
    e_imageseiko6_path: "db/seed_images/棒銀３成功６.png",
    e_imageseiko7_path: "db/seed_images/棒銀３成功７.png"
  },
  {
    content: "棒銀に関するクイズ問題その4。この局面で最善手は？",
    image_path: "db/seed_images/棒銀４.png",
    pattern: "棒銀",
    option1_path: "db/seed_images/棒銀４失敗１.png",
    option2_path: "db/seed_images/棒銀４成功１.png",
    correct: 2,
    e_imagesippai1_path: "db/seed_images/棒銀４失敗１.png",
    e_imagesippai2_path: "db/seed_images/棒銀４失敗２.png",
    e_imagesippai3_path: "db/seed_images/棒銀４失敗３.png",
    e_imagesippai4_path: "db/seed_images/棒銀４失敗４.png",
    e_imagesippai5_path: "db/seed_images/棒銀４失敗５.png",
    e_imagesippai6_path: "db/seed_images/棒銀４失敗６.png",
    e_imageseiko1_path: "db/seed_images/棒銀４成功１.png",
    e_imageseiko2_path: "db/seed_images/棒銀４成功２.png",
    e_imageseiko3_path: "db/seed_images/棒銀４成功３.png",
    e_imageseiko4_path: "db/seed_images/棒銀４成功４.png",
    e_imageseiko5_path: "db/seed_images/棒銀４成功５.png",
    e_imageseiko6_path: "db/seed_images/棒銀４成功６.png",
    e_imageseiko7_path: "db/seed_images/棒銀４成功７.png",
    e_imageseiko8_path: "db/seed_images/棒銀４成功８.png",
    e_imageseiko9_path: "db/seed_images/棒銀４成功９.png"
  },
  {
    content: "棒銀に関するクイズ問題その5。この局面で最善手は？",
    image_path: "db/seed_images/棒銀５.png",
    pattern: "棒銀",
    option1_path: "db/seed_images/棒銀５成功１.png",
    option2_path: "db/seed_images/棒銀５失敗１.png",
    correct: 1,
    e_imagesippai1_path: "db/seed_images/棒銀５失敗１.png",
    e_imagesippai2_path: "db/seed_images/棒銀５失敗２.png",
    e_imagesippai3_path: "db/seed_images/棒銀５失敗３.png",
    e_imagesippai4_path: "db/seed_images/棒銀５失敗４.png",
    e_imagesippai5_path: "db/seed_images/棒銀５失敗５.png",
    e_imagesippai6_path: "db/seed_images/棒銀５失敗６.png",
    e_imagesippai7_path: "db/seed_images/棒銀５失敗７.png",
    e_imagesippai8_path: "db/seed_images/棒銀５失敗８.png",
    e_imagesippai9_path: "db/seed_images/棒銀５失敗９.png",
    e_imagesippai10_path: "db/seed_images/棒銀５失敗１０.png",
    e_imagesippai11_path: "db/seed_images/棒銀５失敗１１.png",
    e_imagesippai12_path: "db/seed_images/棒銀５失敗１２.png",
    e_imagesippai13_path: "db/seed_images/棒銀５失敗１３.png",
    e_imagesippai14_path: "db/seed_images/棒銀５失敗１４.png",
    e_imageseiko1_path: "db/seed_images/棒銀５成功１.png",
    e_imageseiko2_path: "db/seed_images/棒銀５成功２.png",
    e_imageseiko3_path: "db/seed_images/棒銀５成功３.png",
    e_imageseiko4_path: "db/seed_images/棒銀５成功４.png",
    e_imageseiko5_path: "db/seed_images/棒銀５成功５.png",
    e_imageseiko6_path: "db/seed_images/棒銀５成功６.png",
    e_imageseiko7_path: "db/seed_images/棒銀５成功７.png",
    e_imageseiko8_path: "db/seed_images/棒銀５成功８.png",
    e_imageseiko9_path: "db/seed_images/棒銀５成功９.png",
    e_imageseiko10_path: "db/seed_images/棒銀５成功１０.png",
    e_imageseiko11_path: "db/seed_images/棒銀５成功１１.png"
  },
  {
    content: "棒銀に関するクイズ問題その6。この局面で最善手は？",
    image_path: "db/seed_images/棒銀６.png",
    pattern: "棒銀",
    option1_path: "db/seed_images/棒銀６失敗１.png",
    option2_path: "db/seed_images/棒銀６成功１.png",
    correct: 2,
    e_imagesippai1_path: "db/seed_images/棒銀６失敗１.png",
    e_imagesippai2_path: "db/seed_images/棒銀６失敗２.png",
    e_imagesippai3_path: "db/seed_images/棒銀６失敗３.png",
    e_imagesippai4_path: "db/seed_images/棒銀６失敗４.png",
    e_imagesippai5_path: "db/seed_images/棒銀６失敗５.png",
    e_imagesippai6_path: "db/seed_images/棒銀６失敗６.png",
    e_imagesippai7_path: "db/seed_images/棒銀６失敗７.png",
    e_imagesippai8_path: "db/seed_images/棒銀６失敗８.png",
    e_imagesippai9_path: "db/seed_images/棒銀６失敗９.png",
    e_imagesippai10_path: "db/seed_images/棒銀６失敗１０.png",
    e_imagesippai11_path: "db/seed_images/棒銀６失敗１１.png",
    e_imagesippai12_path: "db/seed_images/棒銀６失敗１２.png",
    e_imagesippai13_path: "db/seed_images/棒銀６失敗１３.png",
    e_imageseiko1_path: "db/seed_images/棒銀６成功１.png",
    e_imageseiko2_path: "db/seed_images/棒銀６成功２.png",
    e_imageseiko3_path: "db/seed_images/棒銀６成功３.png",
    e_imageseiko4_path: "db/seed_images/棒銀６成功４.png",
    e_imageseiko5_path: "db/seed_images/棒銀６成功５.png",
    e_imageseiko6_path: "db/seed_images/棒銀６成功６.png",
    e_imageseiko7_path: "db/seed_images/棒銀６成功７.png",
    e_imageseiko8_path: "db/seed_images/棒銀６成功８.png",
    e_imageseiko9_path: "db/seed_images/棒銀６成功９.png",
    e_imageseiko10_path: "db/seed_images/棒銀６成功１０.png",
    e_imageseiko11_path: "db/seed_images/棒銀６成功１１.png"
  },
  {
    content: "棒銀に関するクイズ問題その7。この局面で最善手は？",
    image_path: "db/seed_images/棒銀７.png",
    pattern: "棒銀",
    option1_path: "db/seed_images/棒銀７成功１.png",
    option2_path: "db/seed_images/棒銀７失敗１.png",
    correct: 1,
    e_imagesippai1_path: "db/seed_images/棒銀７失敗１.png",
    e_imagesippai2_path: "db/seed_images/棒銀７失敗２.png",
    e_imagesippai3_path: "db/seed_images/棒銀７失敗３.png",
    e_imagesippai4_path: "db/seed_images/棒銀７失敗４.png",
    e_imagesippai5_path: "db/seed_images/棒銀７失敗５.png",
    e_imagesippai6_path: "db/seed_images/棒銀７失敗６.png",
    e_imagesippai7_path: "db/seed_images/棒銀７失敗７.png",
    e_imagesippai8_path: "db/seed_images/棒銀７失敗８.png",
    e_imagesippai9_path: "db/seed_images/棒銀７失敗９.png",
    e_imagesippai10_path: "db/seed_images/棒銀７失敗１０.png",
    e_imageseiko1_path: "db/seed_images/棒銀７成功１.png",
    e_imageseiko2_path: "db/seed_images/棒銀７成功２.png",
    e_imageseiko3_path: "db/seed_images/棒銀７成功３.png",
    e_imageseiko4_path: "db/seed_images/棒銀７成功４.png",
    e_imageseiko5_path: "db/seed_images/棒銀７成功５.png",
    e_imageseiko6_path: "db/seed_images/棒銀７成功６.png",
    e_imageseiko7_path: "db/seed_images/棒銀７成功７.png",
    e_imageseiko8_path: "db/seed_images/棒銀７成功８.png",
    e_imageseiko9_path: "db/seed_images/棒銀７成功９.png",
    e_imageseiko10_path: "db/seed_images/棒銀７成功１０.png",
    e_imageseiko11_path: "db/seed_images/棒銀７成功１１.png"
  },
  {
    content: "棒銀に関するクイズ問題その8。この局面で最善手は？",
    image_path: "db/seed_images/棒銀８.png",
    pattern: "棒銀",
    option1_path: "db/seed_images/棒銀８失敗１.png",
    option2_path: "db/seed_images/棒銀８成功１.png",
    correct: 2,
    e_imagesippai1_path: "db/seed_images/棒銀８失敗１.png",
    e_imagesippai2_path: "db/seed_images/棒銀８失敗２.png",
    e_imagesippai3_path: "db/seed_images/棒銀８失敗３.png",
    e_imagesippai4_path: "db/seed_images/棒銀８失敗４.png",
    e_imagesippai5_path: "db/seed_images/棒銀８失敗５.png",
    e_imagesippai6_path: "db/seed_images/棒銀８失敗６.png",
    e_imageseiko1_path: "db/seed_images/棒銀８成功１.png",
    e_imageseiko2_path: "db/seed_images/棒銀８成功２.png",
    e_imageseiko3_path: "db/seed_images/棒銀８成功３.png",
    e_imageseiko4_path: "db/seed_images/棒銀８成功４.png",
    e_imageseiko5_path: "db/seed_images/棒銀８成功５.png",
    e_imageseiko6_path: "db/seed_images/棒銀８成功６.png",
    e_imageseiko7_path: "db/seed_images/棒銀８成功７.png",
    e_imageseiko8_path: "db/seed_images/棒銀８成功８.png",
    e_imageseiko9_path: "db/seed_images/棒銀８成功９.png",
    e_imageseiko10_path: "db/seed_images/棒銀８成功１０.png",
    e_imageseiko11_path: "db/seed_images/棒銀８成功１１.png"
  },
  {
    content: "棒銀に関するクイズ問題その9。この局面で最善手は？",
    image_path: "db/seed_images/棒銀９.png",
    pattern: "棒銀",
    option1_path: "db/seed_images/棒銀９成功１.png",
    option2_path: "db/seed_images/棒銀９失敗１.png",
    correct: 1,
    e_imagesippai1_path: "db/seed_images/棒銀９失敗１.png",
    e_imagesippai2_path: "db/seed_images/棒銀９失敗２.png",
    e_imagesippai3_path: "db/seed_images/棒銀９失敗３.png",
    e_imagesippai4_path: "db/seed_images/棒銀９失敗４.png",
    e_imagesippai5_path: "db/seed_images/棒銀９失敗５.png",
    e_imagesippai6_path: "db/seed_images/棒銀９失敗６.png",
    e_imagesippai7_path: "db/seed_images/棒銀９失敗７.png",
    e_imagesippai8_path: "db/seed_images/棒銀９失敗８.png",
    e_imagesippai9_path: "db/seed_images/棒銀９失敗９.png",
    e_imagesippai10_path: "db/seed_images/棒銀９失敗１０.png",
    e_imagesippai11_path: "db/seed_images/棒銀９失敗１１.png",
    e_imagesippai12_path: "db/seed_images/棒銀９失敗１２.png",
    e_imagesippai13_path: "db/seed_images/棒銀９失敗１３.png",
    e_imagesippai14_path: "db/seed_images/棒銀９失敗１４.png",
    e_imagesippai15_path: "db/seed_images/棒銀９失敗１５.png",
    e_imageseiko1_path: "db/seed_images/棒銀９成功１.png",
    e_imageseiko2_path: "db/seed_images/棒銀９成功２.png",
    e_imageseiko3_path: "db/seed_images/棒銀９成功３.png",
    e_imageseiko4_path: "db/seed_images/棒銀９成功４.png",
    e_imageseiko5_path: "db/seed_images/棒銀９成功５.png",
    e_imageseiko6_path: "db/seed_images/棒銀９成功６.png",
    e_imageseiko7_path: "db/seed_images/棒銀９成功７.png",
    e_imageseiko8_path: "db/seed_images/棒銀９成功８.png",
    e_imageseiko9_path: "db/seed_images/棒銀９成功９.png",
    e_imageseiko10_path: "db/seed_images/棒銀９成功１０.png",
    e_imageseiko11_path: "db/seed_images/棒銀９成功１１.png",
    e_imageseiko12_path: "db/seed_images/棒銀９成功１２.png",
    e_imageseiko13_path: "db/seed_images/棒銀９成功１３.png"
  },
  {
    content: "棒銀に関するクイズ問題その10。この局面で最善手は？",
    image_path: "db/seed_images/棒銀１０.png",
    pattern: "棒銀",
    option1_path: "db/seed_images/棒銀１０失敗１.png",
    option2_path: "db/seed_images/棒銀１０成功１.png",
    correct: 2,
    e_imagesippai1_path: "db/seed_images/棒銀１０失敗１.png",
    e_imagesippai2_path: "db/seed_images/棒銀１０失敗２.png",
    e_imagesippai3_path: "db/seed_images/棒銀１０失敗３.png",
    e_imagesippai4_path: "db/seed_images/棒銀１０失敗４.png",
    e_imagesippai5_path: "db/seed_images/棒銀１０失敗５.png",
    e_imagesippai6_path: "db/seed_images/棒銀１０失敗６.png",
    e_imagesippai7_path: "db/seed_images/棒銀１０失敗７.png",
    e_imagesippai8_path: "db/seed_images/棒銀１０失敗８.png",
    e_imagesippai9_path: "db/seed_images/棒銀１０失敗９.png",
    e_imageseiko1_path: "db/seed_images/棒銀１０成功１.png",
    e_imageseiko2_path: "db/seed_images/棒銀１０成功２.png",
    e_imageseiko3_path: "db/seed_images/棒銀１０成功３.png",
    e_imageseiko4_path: "db/seed_images/棒銀１０成功４.png",
    e_imageseiko5_path: "db/seed_images/棒銀１０成功５.png",
    e_imageseiko6_path: "db/seed_images/棒銀１０成功６.png",
    e_imageseiko7_path: "db/seed_images/棒銀１０成功７.png",
    e_imageseiko8_path: "db/seed_images/棒銀１０成功８.png",
    e_imageseiko9_path: "db/seed_images/棒銀１０成功９.png",
    e_imageseiko10_path: "db/seed_images/棒銀１０成功１０.png",
    e_imageseiko11_path: "db/seed_images/棒銀１０成功１１.png"
  }
]
  questions.each do |q|
  question = Question.create!(
    content: q[:content],
    pattern: q[:pattern],
    correct: q[:correct]
  )
  question.image.attach(
    io: File.open(Rails.root.join(q[:image_path])),
    filename: File.basename(q[:image_path]),
    content_type: "image/png"
  )
  question.option1.attach(
    io: File.open(Rails.root.join(q[:option1_path])),
    filename: File.basename(q[:option1_path]),
    content_type: "image/png"
  )
  question.option2.attach(
    io: File.open(Rails.root.join(q[:option2_path])),
    filename: File.basename(q[:option2_path]),
    content_type: "image/png"
  )

    q.each do |key, path|
    # e_image で始まるキーだけ拾う（例: :e_imagesippai1_path）
    next unless key.to_s.start_with?("e_image")
    next if path.blank?
    # :e_imagesippai1_path → "e_imagesippai1"
    attachment_name = key.to_s.sub(/_path\z/, "")
    # Question モデルの ActiveStorage に attach
    question.public_send(attachment_name).attach(
      io: File.open(Rails.root.join(path)),
      filename: File.basename(path),
      content_type: "image/png"
    )
  end
end
