questions = [
{
    content: "奇襲戦法に関するクイズ問題その1。この局面で最善手は？",
    image_path: "db/seed_images/鬼殺し１.png",
    pattern: "奇襲戦法",
    option1_path: "db/seed_images/鬼殺し１成功１.png",
    option2_path: "db/seed_images/鬼殺し１失敗１.png",
    correct: 1,
    e_imagesippai1_path: "db/seed_images/鬼殺し１失敗１.png",
    e_imagesippai2_path: "db/seed_images/鬼殺し１失敗２.png",
    e_imagesippai3_path: "db/seed_images/鬼殺し１失敗３.png",
    e_imagesippai4_path: "db/seed_images/鬼殺し１失敗４.png",
    e_imagesippai5_path: "db/seed_images/鬼殺し１失敗５.png",
    e_imagesippai6_path: "db/seed_images/鬼殺し１失敗６.png",
    e_imagesippai7_path: "db/seed_images/鬼殺し１失敗７.png",
    e_imagesippai8_path: "db/seed_images/鬼殺し１失敗８.png",
    e_imagesippai9_path: "db/seed_images/鬼殺し１失敗９.png",
    e_imagesippai10_path: "db/seed_images/鬼殺し１失敗１０.png",
    e_imageseiko1_path: "db/seed_images/鬼殺し１成功１.png",
    e_imageseiko2_path: "db/seed_images/鬼殺し１成功２.png",
    e_imageseiko3_path: "db/seed_images/鬼殺し１成功３.png",
    e_imageseiko4_path: "db/seed_images/鬼殺し１成功４.png",
    e_imageseiko5_path: "db/seed_images/鬼殺し１成功５.png"
  },
  {
    content: "奇襲戦法に関するクイズ問題その2。この局面で最善手は？",
    image_path: "db/seed_images/鬼殺し２.png",
    pattern: "奇襲戦法",
    option1_path: "db/seed_images/鬼殺し２失敗１.png",
    option2_path: "db/seed_images/鬼殺し２成功１.png",
    correct: 2,
    e_imagesippai1_path: "db/seed_images/鬼殺し２失敗１.png",
    e_imagesippai2_path: "db/seed_images/鬼殺し２失敗２.png",
    e_imagesippai3_path: "db/seed_images/鬼殺し２失敗３.png",
    e_imagesippai4_path: "db/seed_images/鬼殺し２失敗４.png",
    e_imageseiko1_path: "db/seed_images/鬼殺し２成功１.png",
    e_imageseiko2_path: "db/seed_images/鬼殺し２成功２.png",
    e_imageseiko3_path: "db/seed_images/鬼殺し２成功３.png"
  },
  {
    content: "奇襲戦法に関するクイズ問題その3。この局面で最善手は？",
    image_path: "db/seed_images/鬼殺し３.png",
    pattern: "奇襲戦法",
    option1_path: "db/seed_images/鬼殺し３成功１.png",
    option2_path: "db/seed_images/鬼殺し３失敗１.png",
    correct: 1,
    e_imagesippai1_path: "db/seed_images/鬼殺し３失敗１.png",
    e_imagesippai2_path: "db/seed_images/鬼殺し３失敗２.png",
    e_imagesippai3_path: "db/seed_images/鬼殺し３失敗３.png",
    e_imagesippai4_path: "db/seed_images/鬼殺し３失敗４.png",
    e_imagesippai5_path: "db/seed_images/鬼殺し３失敗５.png",
    e_imagesippai6_path: "db/seed_images/鬼殺し３失敗６.png",
    e_imagesippai7_path: "db/seed_images/鬼殺し３失敗７.png",
    e_imagesippai8_path: "db/seed_images/鬼殺し３失敗８.png",
    e_imagesippai9_path: "db/seed_images/鬼殺し３失敗９.png",
    e_imageseiko1_path: "db/seed_images/鬼殺し３成功１.png",
    e_imageseiko2_path: "db/seed_images/鬼殺し３成功２.png",
    e_imageseiko3_path: "db/seed_images/鬼殺し３成功３.png",
    e_imageseiko4_path: "db/seed_images/鬼殺し３成功４.png",
    e_imageseiko5_path: "db/seed_images/鬼殺し３成功５.png",
    e_imageseiko6_path: "db/seed_images/鬼殺し３成功６.png",
    e_imageseiko7_path: "db/seed_images/鬼殺し３成功７.png",
    e_imageseiko8_path: "db/seed_images/鬼殺し３成功８.png",
    e_imageseiko9_path: "db/seed_images/鬼殺し３成功９.png"
  },
  {
    content: "奇襲戦法に関するクイズ問題その4。この局面で最善手は？",
    image_path: "db/seed_images/鬼殺し４.png",
    pattern: "奇襲戦法",
    option1_path: "db/seed_images/鬼殺し４失敗１.png",
    option2_path: "db/seed_images/鬼殺し４成功１.png",
    correct: 2,
    e_imagesippai1_path: "db/seed_images/鬼殺し４失敗１.png",
    e_imagesippai2_path: "db/seed_images/鬼殺し４失敗２.png",
    e_imagesippai3_path: "db/seed_images/鬼殺し４失敗３.png",
    e_imagesippai4_path: "db/seed_images/鬼殺し４失敗４.png",
    e_imagesippai5_path: "db/seed_images/鬼殺し４失敗５.png",
    e_imagesippai6_path: "db/seed_images/鬼殺し４失敗６.png",
    e_imagesippai7_path: "db/seed_images/鬼殺し４失敗７.png",
    e_imagesippai8_path: "db/seed_images/鬼殺し４失敗８.png",
    e_imagesippai9_path: "db/seed_images/鬼殺し４失敗９.png",
    e_imagesippai10_path: "db/seed_images/鬼殺し４失敗１０.png",
    e_imageseiko1_path: "db/seed_images/鬼殺し４成功１.png",
    e_imageseiko2_path: "db/seed_images/鬼殺し４成功２.png",
    e_imageseiko3_path: "db/seed_images/鬼殺し４成功３.png",
    e_imageseiko4_path: "db/seed_images/鬼殺し４成功４.png",
    e_imageseiko5_path: "db/seed_images/鬼殺し４成功５.png",
    e_imageseiko6_path: "db/seed_images/鬼殺し４成功６.png",
    e_imageseiko7_path: "db/seed_images/鬼殺し４成功７.png",
    e_imageseiko8_path: "db/seed_images/鬼殺し４成功８.png",
    e_imageseiko9_path: "db/seed_images/鬼殺し４成功９.png"
  },
  {
    content: "奇襲戦法に関するクイズ問題その5。この局面で最善手は？",
    image_path: "db/seed_images/鬼殺し５.png",
    pattern: "奇襲戦法",
    option1_path: "db/seed_images/鬼殺し５成功１.png",
    option2_path: "db/seed_images/鬼殺し５失敗１.png",
    correct: 1,
    e_imagesippai1_path: "db/seed_images/鬼殺し５失敗１.png",
    e_imagesippai2_path: "db/seed_images/鬼殺し５失敗２.png",
    e_imagesippai3_path: "db/seed_images/鬼殺し５失敗３.png",
    e_imagesippai4_path: "db/seed_images/鬼殺し５失敗４.png",
    e_imagesippai5_path: "db/seed_images/鬼殺し５失敗５.png",
    e_imagesippai6_path: "db/seed_images/鬼殺し５失敗６.png",
    e_imageseiko1_path: "db/seed_images/鬼殺し５成功１.png",
    e_imageseiko2_path: "db/seed_images/鬼殺し５成功２.png",
    e_imageseiko3_path: "db/seed_images/鬼殺し５成功３.png",
    e_imageseiko4_path: "db/seed_images/鬼殺し５成功４.png",
    e_imageseiko5_path: "db/seed_images/鬼殺し５成功５.png",
    e_imageseiko6_path: "db/seed_images/鬼殺し５成功６.png",
    e_imageseiko7_path: "db/seed_images/鬼殺し５成功７.png"
  },
  {
    content: "奇襲戦法に関するクイズ問題その6。この局面で最善手は？",
    image_path: "db/seed_images/早石田１.png",
    pattern: "奇襲戦法",
    option1_path: "db/seed_images/早石田１失敗１.png",
    option2_path: "db/seed_images/早石田１成功１.png",
    correct: 2,
    e_imagesippai1_path: "db/seed_images/早石田１失敗１.png",
    e_imagesippai2_path: "db/seed_images/早石田１失敗２.png",
    e_imagesippai3_path: "db/seed_images/早石田１失敗３.png",
    e_imagesippai4_path: "db/seed_images/早石田１失敗４.png",
    e_imageseiko1_path: "db/seed_images/早石田１成功１.png",
    e_imageseiko2_path: "db/seed_images/早石田１成功２.png",
    e_imageseiko3_path: "db/seed_images/早石田１成功３.png",
    e_imageseiko4_path: "db/seed_images/早石田１成功４.png",
    e_imageseiko5_path: "db/seed_images/早石田１成功５.png"
  },
  {
    content: "奇襲戦法に関するクイズ問題その7。この局面で最善手は？",
    image_path: "db/seed_images/早石田２.png",
    pattern: "奇襲戦法",
    option1_path: "db/seed_images/早石田２成功１.png",
    option2_path: "db/seed_images/早石田２失敗１.png",
    correct: 1,
    e_imagesippai1_path: "db/seed_images/早石田２失敗１.png",
    e_imagesippai2_path: "db/seed_images/早石田２失敗２.png",
    e_imagesippai3_path: "db/seed_images/早石田２失敗３.png",
    e_imagesippai4_path: "db/seed_images/早石田２失敗４.png",
    e_imagesippai5_path: "db/seed_images/早石田２失敗５.png",
    e_imagesippai6_path: "db/seed_images/早石田２失敗６.png",
    e_imagesippai7_path: "db/seed_images/早石田２失敗７.png",
    e_imagesippai8_path: "db/seed_images/早石田２失敗８.png",
    e_imageseiko1_path: "db/seed_images/早石田２成功１.png",
    e_imageseiko2_path: "db/seed_images/早石田２成功２.png",
    e_imageseiko3_path: "db/seed_images/早石田２成功３.png",
    e_imageseiko4_path: "db/seed_images/早石田２成功４.png",
    e_imageseiko5_path: "db/seed_images/早石田２成功５.png"
  },
  {
    content: "奇襲戦法に関するクイズ問題その8。この局面で最善手は？",
    image_path: "db/seed_images/早石田３.png",
    pattern: "奇襲戦法",
    option1_path: "db/seed_images/早石田３失敗１.png",
    option2_path: "db/seed_images/早石田３成功１.png",
    correct: 2,
    e_imagesippai1_path: "db/seed_images/早石田３失敗１.png",
    e_imagesippai2_path: "db/seed_images/早石田３失敗２.png",
    e_imagesippai3_path: "db/seed_images/早石田３失敗３.png",
    e_imagesippai4_path: "db/seed_images/早石田３失敗４.png",
    e_imageseiko1_path: "db/seed_images/早石田３成功１.png",
    e_imageseiko2_path: "db/seed_images/早石田３成功２.png",
    e_imageseiko3_path: "db/seed_images/早石田３成功３.png"
  },
  {
    content: "奇襲戦法に関するクイズ問題その9。この局面で最善手は？",
    image_path: "db/seed_images/早石田４.png",
    pattern: "奇襲戦法",
    option1_path: "db/seed_images/早石田４成功１.png",
    option2_path: "db/seed_images/早石田４失敗１.png",
    correct: 1,
    e_imagesippai1_path: "db/seed_images/早石田４失敗１.png",
    e_imagesippai2_path: "db/seed_images/早石田４失敗２.png",
    e_imagesippai3_path: "db/seed_images/早石田４失敗３.png",
    e_imagesippai4_path: "db/seed_images/早石田４失敗４.png",
    e_imagesippai5_path: "db/seed_images/早石田４失敗５.png",
    e_imagesippai6_path: "db/seed_images/早石田４失敗６.png",
    e_imagesippai7_path: "db/seed_images/早石田４失敗７.png",
    e_imagesippai8_path: "db/seed_images/早石田４失敗８.png",
    e_imagesippai9_path: "db/seed_images/早石田４失敗９.png",
    e_imagesippai10_path: "db/seed_images/早石田４失敗４.png",
    e_imagesippai11_path: "db/seed_images/早石田４失敗１１.png",
    e_imagesippai12_path: "db/seed_images/早石田４失敗１２.png",
    e_imagesippai13_path: "db/seed_images/早石田４失敗１３.png",
    e_imagesippai14_path: "db/seed_images/早石田４失敗１４.png",
    e_imagesippai15_path: "db/seed_images/早石田４失敗１５.png",
    e_imagesippai16_path: "db/seed_images/早石田４失敗１６.png",
    e_imagesippai17_path: "db/seed_images/早石田４失敗１７.png",
    e_imagesippai18_path: "db/seed_images/早石田４失敗１８.png",
    e_imageseiko1_path: "db/seed_images/早石田４成功１.png",
    e_imageseiko2_path: "db/seed_images/早石田４成功２.png",
    e_imageseiko3_path: "db/seed_images/早石田４成功３.png",
    e_imageseiko4_path: "db/seed_images/早石田４成功４.png",
    e_imageseiko5_path: "db/seed_images/早石田４成功５.png",
    e_imageseiko6_path: "db/seed_images/早石田４成功６.png",
    e_imageseiko7_path: "db/seed_images/早石田４成功７.png",
    e_imageseiko8_path: "db/seed_images/早石田４成功８.png",
    e_imageseiko9_path: "db/seed_images/早石田４成功９.png"
  },
  {
    content: "奇襲戦法に関するクイズ問題その10。この局面で最善手は？",
    image_path: "db/seed_images/早石田５.png",
    pattern: "奇襲戦法",
    option1_path: "db/seed_images/早石田５失敗１.png",
    option2_path: "db/seed_images/早石田５成功１.png",
    correct: 2,
    e_imagesippai1_path: "db/seed_images/早石田５失敗１.png",
    e_imagesippai2_path: "db/seed_images/早石田５失敗２.png",
    e_imagesippai3_path: "db/seed_images/早石田５失敗３.png",
    e_imagesippai4_path: "db/seed_images/早石田５失敗４.png",
    e_imagesippai5_path: "db/seed_images/早石田５失敗５.png",
    e_imagesippai6_path: "db/seed_images/早石田５失敗６.png",
    e_imageseiko1_path: "db/seed_images/早石田５成功１.png",
    e_imageseiko2_path: "db/seed_images/早石田５成功２.png",
    e_imageseiko3_path: "db/seed_images/早石田５成功３.png",
    e_imageseiko4_path: "db/seed_images/早石田５成功４.png",
    e_imageseiko5_path: "db/seed_images/早石田５成功５.png"
  }
]
  questions.each do |q|
  question = Question.create!(
    content: q[:content],
    pattern: q[:pattern],
    correct: q[:correct]
  )
  question.image.attach(
    io: File.open(Rails.root.join(q[:image_path])),
    filename: File.basename(q[:image_path]),
    content_type: "image/png"
  )
  question.option1.attach(
    io: File.open(Rails.root.join(q[:option1_path])),
    filename: File.basename(q[:option1_path]),
    content_type: "image/png"
  )
  question.option2.attach(
    io: File.open(Rails.root.join(q[:option2_path])),
    filename: File.basename(q[:option2_path]),
    content_type: "image/png"
  )

    q.each do |key, path|
    # e_image で始まるキーだけ拾う（例: :e_imagesippai1_path）
    next unless key.to_s.start_with?("e_image")
    next if path.blank?
    # :e_imagesippai1_path → "e_imagesippai1"
    attachment_name = key.to_s.sub(/_path\z/, "")
    # Question モデルの ActiveStorage に attach
    question.public_send(attachment_name).attach(
      io: File.open(Rails.root.join(path)),
      filename: File.basename(path),
      content_type: "image/png"
    )
  end
end
