questions = [
{
    content: "中飛車に関するクイズ問題その1。この局面で最善手は？",
    image_path: "db/seed_images/ゴキゲン中飛車１.png",
    pattern: "ゴキゲン中飛車",
    option1_path: "db/seed_images/ゴキゲン中飛車１成功１.png",
    option2_path: "db/seed_images/ゴキゲン中飛車１失敗１.png",
    correct: 1,
    e_imagesippai1_path: "db/seed_images/ゴキゲン中飛車１失敗１.png",
    e_imagesippai2_path: "db/seed_images/ゴキゲン中飛車１失敗２.png",
    e_imagesippai3_path: "db/seed_images/ゴキゲン中飛車１失敗３.png",
    e_imagesippai4_path: "db/seed_images/ゴキゲン中飛車１失敗４.png",
    e_imagesippai5_path: "db/seed_images/ゴキゲン中飛車１失敗５.png",
    e_imagesippai6_path: "db/seed_images/ゴキゲン中飛車１失敗６.png",
    e_imagesippai7_path: "db/seed_images/ゴキゲン中飛車１失敗７.png",
    e_imagesippai8_path: "db/seed_images/ゴキゲン中飛車１失敗８.png",
    e_imagesippai9_path: "db/seed_images/ゴキゲン中飛車１失敗９.png",
    e_imagesippai10_path: "db/seed_images/ゴキゲン中飛車１失敗１０.png",
    e_imagesippai11_path: "db/seed_images/ゴキゲン中飛車１失敗１１.png",
    e_imagesippai12_path: "db/seed_images/ゴキゲン中飛車１失敗１２.png",
    e_imagesippai13_path: "db/seed_images/ゴキゲン中飛車１失敗１３.png",
    e_imagesippai14_path: "db/seed_images/ゴキゲン中飛車１失敗１４.png",
    e_imagesippai15_path: "db/seed_images/ゴキゲン中飛車１失敗１５.png",
    e_imagesippai16_path: "db/seed_images/ゴキゲン中飛車１失敗１６.png",
    e_imagesippai17_path: "db/seed_images/ゴキゲン中飛車１失敗１７.png",
    e_imageseiko1_path: "db/seed_images/ゴキゲン中飛車１成功１.png",
    e_imageseiko2_path: "db/seed_images/ゴキゲン中飛車１成功２.png",
    e_imageseiko3_path: "db/seed_images/ゴキゲン中飛車１成功３.png",
    e_imageseiko4_path: "db/seed_images/ゴキゲン中飛車１成功４.png",
    e_imageseiko5_path: "db/seed_images/ゴキゲン中飛車１成功５.png",
    e_imageseiko6_path: "db/seed_images/ゴキゲン中飛車１成功６.png",
    e_imageseiko7_path: "db/seed_images/ゴキゲン中飛車１成功７.png",
    e_imageseiko8_path: "db/seed_images/ゴキゲン中飛車１成功８.png",
    e_imageseiko9_path: "db/seed_images/ゴキゲン中飛車１成功９.png",
    e_imageseiko10_path: "db/seed_images/ゴキゲン中飛車１成功１０.png"
  },
  {
    content: "中飛車に関するクイズ問題その2。この局面で最善手は？",
    image_path: "db/seed_images/ゴキゲン中飛車２.png",
    pattern: "ゴキゲン中飛車",
    option1_path: "db/seed_images/ゴキゲン中飛車２失敗１.png",
    option2_path: "db/seed_images/ゴキゲン中飛車２成功１.png",
    correct: 2,
    e_imagesippai1_path: "db/seed_images/ゴキゲン中飛車２失敗１.png",
    e_imagesippai2_path: "db/seed_images/ゴキゲン中飛車２失敗２.png",
    e_imagesippai3_path: "db/seed_images/ゴキゲン中飛車２失敗３.png",
    e_imagesippai4_path: "db/seed_images/ゴキゲン中飛車２失敗４.png",
    e_imagesippai5_path: "db/seed_images/ゴキゲン中飛車２失敗５.png",
    e_imagesippai6_path: "db/seed_images/ゴキゲン中飛車２失敗６.png",
    e_imageseiko1_path: "db/seed_images/ゴキゲン中飛車２成功１.png",
    e_imageseiko2_path: "db/seed_images/ゴキゲン中飛車２成功２.png",
    e_imageseiko3_path: "db/seed_images/ゴキゲン中飛車２成功３.png",
    e_imageseiko4_path: "db/seed_images/ゴキゲン中飛車２成功４.png",
    e_imageseiko5_path: "db/seed_images/ゴキゲン中飛車２成功５.png",
    e_imageseiko6_path: "db/seed_images/ゴキゲン中飛車２成功６.png",
    e_imageseiko7_path: "db/seed_images/ゴキゲン中飛車２成功７.png"
  },
  {
    content: "中飛車に関するクイズ問題その3。この局面で最善手は？",
    image_path: "db/seed_images/ゴキゲン中飛車３.png",
    pattern: "ゴキゲン中飛車",
    option1_path: "db/seed_images/ゴキゲン中飛車３成功１.png",
    option2_path: "db/seed_images/ゴキゲン中飛車３失敗１.png",
    correct: 1,
    e_imagesippai1_path: "db/seed_images/ゴキゲン中飛車３失敗１.png",
    e_imagesippai2_path: "db/seed_images/ゴキゲン中飛車３失敗２.png",
    e_imagesippai3_path: "db/seed_images/ゴキゲン中飛車３失敗３.png",
    e_imagesippai4_path: "db/seed_images/ゴキゲン中飛車３失敗４.png",
    e_imagesippai5_path: "db/seed_images/ゴキゲン中飛車３失敗５.png",
    e_imagesippai6_path: "db/seed_images/ゴキゲン中飛車３失敗６.png",
    e_imagesippai7_path: "db/seed_images/ゴキゲン中飛車３失敗７.png",
    e_imagesippai8_path: "db/seed_images/ゴキゲン中飛車３失敗８.png",
    e_imagesippai9_path: "db/seed_images/ゴキゲン中飛車３失敗９.png",
    e_imagesippai10_path: "db/seed_images/ゴキゲン中飛車３失敗１０.png",
    e_imagesippai11_path: "db/seed_images/ゴキゲン中飛車３失敗１１.png",
    e_imagesippai12_path: "db/seed_images/ゴキゲン中飛車３失敗１２.png",
    e_imagesippai13_path: "db/seed_images/ゴキゲン中飛車３失敗１３.png",
    e_imagesippai14_path: "db/seed_images/ゴキゲン中飛車３失敗１４.png",
    e_imagesippai15_path: "db/seed_images/ゴキゲン中飛車３失敗１５.png",
    e_imagesippai16_path: "db/seed_images/ゴキゲン中飛車３失敗１６.png",
    e_imagesippai17_path: "db/seed_images/ゴキゲン中飛車３失敗１７.png",
    e_imagesippai18_path: "db/seed_images/ゴキゲン中飛車３失敗１８.png",
    e_imagesippai19_path: "db/seed_images/ゴキゲン中飛車３失敗１９.png",
    e_imagesippai20_path: "db/seed_images/ゴキゲン中飛車３失敗２０.png",
    e_imageseiko1_path: "db/seed_images/ゴキゲン中飛車３成功１.png",
    e_imageseiko2_path: "db/seed_images/ゴキゲン中飛車３成功２.png",
    e_imageseiko3_path: "db/seed_images/ゴキゲン中飛車３成功３.png",
    e_imageseiko4_path: "db/seed_images/ゴキゲン中飛車３成功４.png",
    e_imageseiko5_path: "db/seed_images/ゴキゲン中飛車３成功５.png",
    e_imageseiko6_path: "db/seed_images/ゴキゲン中飛車３成功６.png",
    e_imageseiko7_path: "db/seed_images/ゴキゲン中飛車３成功７.png",
    e_imageseiko8_path: "db/seed_images/ゴキゲン中飛車３成功８.png",
    e_imageseiko9_path: "db/seed_images/ゴキゲン中飛車３成功９.png"
  },
  {
    content: "中飛車に関するクイズ問題その4。この局面で最善手は？",
    image_path: "db/seed_images/ゴキゲン中飛車４.png",
    pattern: "ゴキゲン中飛車",
    option1_path: "db/seed_images/ゴキゲン中飛車４失敗１.png",
    option2_path: "db/seed_images/ゴキゲン中飛車４成功１.png",
    correct: 2,
    e_imagesippai1_path: "db/seed_images/ゴキゲン中飛車４失敗１.png",
    e_imagesippai2_path: "db/seed_images/ゴキゲン中飛車４失敗２.png",
    e_imagesippai3_path: "db/seed_images/ゴキゲン中飛車４失敗３.png",
    e_imagesippai4_path: "db/seed_images/ゴキゲン中飛車４失敗４.png",
    e_imageseiko1_path: "db/seed_images/ゴキゲン中飛車４成功１.png",
    e_imageseiko2_path: "db/seed_images/ゴキゲン中飛車４成功２.png",
    e_imageseiko3_path: "db/seed_images/ゴキゲン中飛車４成功３.png",
    e_imageseiko4_path: "db/seed_images/ゴキゲン中飛車４成功４.png",
    e_imageseiko5_path: "db/seed_images/ゴキゲン中飛車４成功５.png",
    e_imageseiko6_path: "db/seed_images/ゴキゲン中飛車４成功６.png",
    e_imageseiko7_path: "db/seed_images/ゴキゲン中飛車４成功７.png",
    e_imageseiko8_path: "db/seed_images/ゴキゲン中飛車４成功８.png",
    e_imageseiko9_path: "db/seed_images/ゴキゲン中飛車４成功９.png",
    e_imageseiko10_path: "db/seed_images/ゴキゲン中飛車４成功１０.png",
    e_imageseiko11_path: "db/seed_images/ゴキゲン中飛車４成功１１.png",
    e_imageseiko12_path: "db/seed_images/ゴキゲン中飛車４成功１２.png",
    e_imageseiko13_path: "db/seed_images/ゴキゲン中飛車４成功１３.png"
  },
  {
    content: "中飛車に関するクイズ問題その5。この局面で最善手は？",
    image_path: "db/seed_images/ゴキゲン中飛車５.png",
    pattern: "ゴキゲン中飛車",
    option1_path: "db/seed_images/ゴキゲン中飛車５成功１.png",
    option2_path: "db/seed_images/ゴキゲン中飛車５失敗１.png",
    correct: 1,
    e_imagesippai1_path: "db/seed_images/ゴキゲン中飛車５失敗１.png",
    e_imagesippai2_path: "db/seed_images/ゴキゲン中飛車５失敗２.png",
    e_imagesippai3_path: "db/seed_images/ゴキゲン中飛車５失敗３.png",
    e_imagesippai4_path: "db/seed_images/ゴキゲン中飛車５失敗４.png",
    e_imagesippai5_path: "db/seed_images/ゴキゲン中飛車５失敗５.png",
    e_imagesippai6_path: "db/seed_images/ゴキゲン中飛車５失敗６.png",
    e_imagesippai7_path: "db/seed_images/ゴキゲン中飛車５失敗７.png",
    e_imagesippai8_path: "db/seed_images/ゴキゲン中飛車５失敗８.png",
    e_imagesippai9_path: "db/seed_images/ゴキゲン中飛車５失敗９.png",
    e_imagesippai10_path: "db/seed_images/ゴキゲン中飛車５失敗１０.png",
    e_imagesippai11_path: "db/seed_images/ゴキゲン中飛車５失敗１１.png",
    e_imagesippai12_path: "db/seed_images/ゴキゲン中飛車５失敗１２.png",
    e_imagesippai13_path: "db/seed_images/ゴキゲン中飛車５失敗１３.png",
    e_imagesippai14_path: "db/seed_images/ゴキゲン中飛車５失敗１４.png",
    e_imageseiko1_path: "db/seed_images/ゴキゲン中飛車５成功１.png",
    e_imageseiko2_path: "db/seed_images/ゴキゲン中飛車５成功２.png",
    e_imageseiko3_path: "db/seed_images/ゴキゲン中飛車５成功３.png",
    e_imageseiko4_path: "db/seed_images/ゴキゲン中飛車５成功４.png",
    e_imageseiko5_path: "db/seed_images/ゴキゲン中飛車５成功５.png",
    e_imageseiko6_path: "db/seed_images/ゴキゲン中飛車５成功６.png",
    e_imageseiko7_path: "db/seed_images/ゴキゲン中飛車５成功７.png"
  },
  {
    content: "中飛車に関するクイズ問題その6。この局面で最善手は？",
    image_path: "db/seed_images/ゴキゲン中飛車６.png",
    pattern: "ゴキゲン中飛車",
    option1_path: "db/seed_images/ゴキゲン中飛車６失敗１.png",
    option2_path: "db/seed_images/ゴキゲン中飛車６成功１.png",
    correct: 2,
    e_imagesippai1_path: "db/seed_images/ゴキゲン中飛車６失敗１.png",
    e_imagesippai2_path: "db/seed_images/ゴキゲン中飛車６失敗２.png",
    e_imagesippai3_path: "db/seed_images/ゴキゲン中飛車６失敗３.png",
    e_imageseiko1_path: "db/seed_images/ゴキゲン中飛車６成功１.png",
    e_imageseiko2_path: "db/seed_images/ゴキゲン中飛車６成功２.png",
    e_imageseiko3_path: "db/seed_images/ゴキゲン中飛車６成功３.png",
    e_imageseiko4_path: "db/seed_images/ゴキゲン中飛車６成功４.png",
    e_imageseiko5_path: "db/seed_images/ゴキゲン中飛車６成功５.png",
    e_imageseiko6_path: "db/seed_images/ゴキゲン中飛車６成功６.png",
    e_imageseiko7_path: "db/seed_images/ゴキゲン中飛車６成功７.png"
  },
  {
    content: "中飛車に関するクイズ問題その7。この局面で最善手は？",
    image_path: "db/seed_images/ゴキゲン中飛車７.png",
    pattern: "ゴキゲン中飛車",
    option1_path: "db/seed_images/ゴキゲン中飛車７成功１.png",
    option2_path: "db/seed_images/ゴキゲン中飛車７失敗１.png",
    correct: 1,
    e_imagesippai1_path: "db/seed_images/ゴキゲン中飛車７失敗１.png",
    e_imagesippai2_path: "db/seed_images/ゴキゲン中飛車７失敗２.png",
    e_imagesippai3_path: "db/seed_images/ゴキゲン中飛車７失敗３.png",
    e_imagesippai4_path: "db/seed_images/ゴキゲン中飛車７失敗４.png",
    e_imagesippai5_path: "db/seed_images/ゴキゲン中飛車７失敗５.png",
    e_imagesippai6_path: "db/seed_images/ゴキゲン中飛車７失敗６.png",
    e_imagesippai7_path: "db/seed_images/ゴキゲン中飛車７失敗７.png",
    e_imagesippai8_path: "db/seed_images/ゴキゲン中飛車７失敗８.png",
    e_imagesippai9_path: "db/seed_images/ゴキゲン中飛車７失敗９.png",
    e_imagesippai10_path: "db/seed_images/ゴキゲン中飛車７失敗１０.png",
    e_imagesippai11_path: "db/seed_images/ゴキゲン中飛車７失敗１１.png",
    e_imagesippai12_path: "db/seed_images/ゴキゲン中飛車７失敗１２.png",
    e_imagesippai13_path: "db/seed_images/ゴキゲン中飛車７失敗１３.png",
    e_imageseiko1_path: "db/seed_images/ゴキゲン中飛車７成功１.png",
    e_imageseiko2_path: "db/seed_images/ゴキゲン中飛車７成功２.png",
    e_imageseiko3_path: "db/seed_images/ゴキゲン中飛車７成功３.png",
    e_imageseiko4_path: "db/seed_images/ゴキゲン中飛車７成功４.png",
    e_imageseiko5_path: "db/seed_images/ゴキゲン中飛車７成功５.png"
  },
  {
    content: "中飛車に関するクイズ問題その8。この局面で最善手は？",
    image_path: "db/seed_images/ゴキゲン中飛車８.png",
    pattern: "ゴキゲン中飛車",
    option1_path: "db/seed_images/ゴキゲン中飛車８失敗１.png",
    option2_path: "db/seed_images/ゴキゲン中飛車８成功１.png",
    correct: 2,
    e_imagesippai1_path: "db/seed_images/ゴキゲン中飛車８失敗１.png",
    e_imagesippai2_path: "db/seed_images/ゴキゲン中飛車８失敗２.png",
    e_imagesippai3_path: "db/seed_images/ゴキゲン中飛車８失敗３.png",
    e_imagesippai4_path: "db/seed_images/ゴキゲン中飛車８失敗４.png",
    e_imagesippai5_path: "db/seed_images/ゴキゲン中飛車８失敗５.png",
    e_imagesippai6_path: "db/seed_images/ゴキゲン中飛車８失敗６.png",
    e_imagesippai7_path: "db/seed_images/ゴキゲン中飛車８失敗７.png",
    e_imagesippai8_path: "db/seed_images/ゴキゲン中飛車８失敗８.png",
    e_imagesippai9_path: "db/seed_images/ゴキゲン中飛車８失敗９.png",
    e_imagesippai10_path: "db/seed_images/ゴキゲン中飛車８失敗１０.png",
    e_imagesippai11_path: "db/seed_images/ゴキゲン中飛車８失敗１１.png",
    e_imagesippai12_path: "db/seed_images/ゴキゲン中飛車８失敗１２.png",
    e_imageseiko1_path: "db/seed_images/ゴキゲン中飛車８成功１.png",
    e_imageseiko2_path: "db/seed_images/ゴキゲン中飛車８成功２.png",
    e_imageseiko3_path: "db/seed_images/ゴキゲン中飛車８成功３.png",
    e_imageseiko4_path: "db/seed_images/ゴキゲン中飛車８成功４.png",
    e_imageseiko5_path: "db/seed_images/ゴキゲン中飛車８成功５.png",
    e_imageseiko6_path: "db/seed_images/ゴキゲン中飛車８成功６.png",
    e_imageseiko7_path: "db/seed_images/ゴキゲン中飛車８成功７.png",
    e_imageseiko8_path: "db/seed_images/ゴキゲン中飛車８成功８.png",
    e_imageseiko9_path: "db/seed_images/ゴキゲン中飛車８成功９.png",
    e_imageseiko10_path: "db/seed_images/ゴキゲン中飛車８成功１０.png",
    e_imageseiko11_path: "db/seed_images/ゴキゲン中飛車８成功１１.png",
    e_imageseiko12_path: "db/seed_images/ゴキゲン中飛車８成功１２.png",
    e_imageseiko13_path: "db/seed_images/ゴキゲン中飛車８成功１３.png"
  },
  {
    content: "中飛車に関するクイズ問題その9。この局面で最善手は？",
    image_path: "db/seed_images/ゴキゲン中飛車９.png",
    pattern: "ゴキゲン中飛車",
    option1_path: "db/seed_images/ゴキゲン中飛車９成功１.png",
    option2_path: "db/seed_images/ゴキゲン中飛車９失敗１.png",
    correct: 1,
    e_imagesippai1_path: "db/seed_images/ゴキゲン中飛車９失敗１.png",
    e_imagesippai2_path: "db/seed_images/ゴキゲン中飛車９失敗２.png",
    e_imagesippai3_path: "db/seed_images/ゴキゲン中飛車９失敗３.png",
    e_imagesippai4_path: "db/seed_images/ゴキゲン中飛車９失敗４.png",
    e_imagesippai5_path: "db/seed_images/ゴキゲン中飛車９失敗５.png",
    e_imagesippai6_path: "db/seed_images/ゴキゲン中飛車９失敗６.png",
    e_imagesippai7_path: "db/seed_images/ゴキゲン中飛車９失敗７.png",
    e_imagesippai8_path: "db/seed_images/ゴキゲン中飛車９失敗８.png",
    e_imageseiko1_path: "db/seed_images/ゴキゲン中飛車９成功１.png",
    e_imageseiko2_path: "db/seed_images/ゴキゲン中飛車９成功２.png",
    e_imageseiko3_path: "db/seed_images/ゴキゲン中飛車９成功３.png",
    e_imageseiko4_path: "db/seed_images/ゴキゲン中飛車９成功４.png",
    e_imageseiko5_path: "db/seed_images/ゴキゲン中飛車９成功５.png",
    e_imageseiko6_path: "db/seed_images/ゴキゲン中飛車９成功６.png",
    e_imageseiko7_path: "db/seed_images/ゴキゲン中飛車９成功７.png",
    e_imageseiko8_path: "db/seed_images/ゴキゲン中飛車９成功８.png",
    e_imageseiko9_path: "db/seed_images/ゴキゲン中飛車９成功９.png",
    e_imageseiko10_path: "db/seed_images/ゴキゲン中飛車９成功１０.png",
    e_imageseiko11_path: "db/seed_images/ゴキゲン中飛車９成功１１.png",
    e_imageseiko12_path: "db/seed_images/ゴキゲン中飛車９成功１２.png",
    e_imageseiko13_path: "db/seed_images/ゴキゲン中飛車９成功１３.png",
    e_imageseiko14_path: "db/seed_images/ゴキゲン中飛車９成功１４.png",
    e_imageseiko15_path: "db/seed_images/ゴキゲン中飛車９成功１５.png",
    e_imageseiko16_path: "db/seed_images/ゴキゲン中飛車９成功１６.png",
    e_imageseiko17_path: "db/seed_images/ゴキゲン中飛車９成功１７.png",
    e_imageseiko18_path: "db/seed_images/ゴキゲン中飛車９成功１８.png",
    e_imageseiko19_path: "db/seed_images/ゴキゲン中飛車９成功１９.png",
    e_imageseiko20_path: "db/seed_images/ゴキゲン中飛車９成功２０.png",
    e_imageseiko21_path: "db/seed_images/ゴキゲン中飛車９成功２１.png",
    e_imageseiko22_path: "db/seed_images/ゴキゲン中飛車９成功２２.png",
    e_imageseiko23_path: "db/seed_images/ゴキゲン中飛車９成功２３.png",
    e_imageseiko24_path: "db/seed_images/ゴキゲン中飛車９成功２４.png",
    e_imageseiko25_path: "db/seed_images/ゴキゲン中飛車９成功２５.png"
  },
  {
    content: "中飛車に関するクイズ問題その10。この局面で最善手は？",
    image_path: "db/seed_images/ゴキゲン中飛車１０.png",
    pattern: "ゴキゲン中飛車",
    option1_path: "db/seed_images/ゴキゲン中飛車１０失敗１.png",
    option2_path: "db/seed_images/ゴキゲン中飛車１０成功１.png",
    correct: 2,
    e_imagesippai1_path: "db/seed_images/ゴキゲン中飛車１０失敗１.png",
    e_imagesippai2_path: "db/seed_images/ゴキゲン中飛車１０失敗２.png",
    e_imagesippai3_path: "db/seed_images/ゴキゲン中飛車１０失敗３.png",
    e_imagesippai4_path: "db/seed_images/ゴキゲン中飛車１０失敗４.png",
    e_imagesippai5_path: "db/seed_images/ゴキゲン中飛車１０失敗５.png",
    e_imagesippai6_path: "db/seed_images/ゴキゲン中飛車１０失敗６.png",
    e_imagesippai7_path: "db/seed_images/ゴキゲン中飛車１０失敗７.png",
    e_imagesippai8_path: "db/seed_images/ゴキゲン中飛車１０失敗８.png",
    e_imagesippai9_path: "db/seed_images/ゴキゲン中飛車１０失敗９.png",
    e_imagesippai10_path: "db/seed_images/ゴキゲン中飛車１０失敗１０.png",
    e_imagesippai11_path: "db/seed_images/ゴキゲン中飛車１０失敗１１.png",
    e_imagesippai12_path: "db/seed_images/ゴキゲン中飛車１０失敗１２.png",
    e_imageseiko1_path: "db/seed_images/ゴキゲン中飛車１０成功１.png",
    e_imageseiko2_path: "db/seed_images/ゴキゲン中飛車１０成功２.png",
    e_imageseiko3_path: "db/seed_images/ゴキゲン中飛車１０成功３.png",
    e_imageseiko4_path: "db/seed_images/ゴキゲン中飛車１０成功４.png",
    e_imageseiko5_path: "db/seed_images/ゴキゲン中飛車１０成功５.png",
    e_imageseiko6_path: "db/seed_images/ゴキゲン中飛車１０成功６.png",
    e_imageseiko7_path: "db/seed_images/ゴキゲン中飛車１０成功７.png"
  }
]
  questions.each do |q|
  question = Question.create!(
    content: q[:content],
    pattern: q[:pattern],
    correct: q[:correct]
  )
  question.image.attach(
    io: File.open(Rails.root.join(q[:image_path])),
    filename: File.basename(q[:image_path]),
    content_type: "image/png"
  )
  question.option1.attach(
    io: File.open(Rails.root.join(q[:option1_path])),
    filename: File.basename(q[:option1_path]),
    content_type: "image/png"
  )
  question.option2.attach(
    io: File.open(Rails.root.join(q[:option2_path])),
    filename: File.basename(q[:option2_path]),
    content_type: "image/png"
  )

    q.each do |key, path|
    # e_image で始まるキーだけ拾う（例: :e_imagesippai1_path）
    next unless key.to_s.start_with?("e_image")
    next if path.blank?
    # :e_imagesippai1_path → "e_imagesippai1"
    attachment_name = key.to_s.sub(/_path\z/, "")
    # Question モデルの ActiveStorage に attach
    question.public_send(attachment_name).attach(
      io: File.open(Rails.root.join(path)),
      filename: File.basename(path),
      content_type: "image/png"
    )
  end
end
