class Question < ApplicationRecord
  has_one_attached :image
  has_one_attached :option1
  has_one_attached :option2
  has_one_attached :e_imageseiko1
  has_one_attached :e_imageseiko2
  has_one_attached :e_imageseiko3
  has_one_attached :e_imageseiko4
  has_one_attached :e_imageseiko5
  has_one_attached :e_imageseiko6
  has_one_attached :e_imageseiko7
  has_one_attached :e_imageseiko8
  has_one_attached :e_imageseiko9
  has_one_attached :e_imageseiko10
  has_one_attached :e_imageseiko11
  has_one_attached :e_imageseiko12
  has_one_attached :e_imageseiko13
  has_one_attached :e_imageseiko14
  has_one_attached :e_imageseiko15
  has_one_attached :e_imageseiko16
  has_one_attached :e_imageseiko17
  has_one_attached :e_imageseiko18
  has_one_attached :e_imageseiko19
  has_one_attached :e_imageseiko20
  has_one_attached :e_imageseiko21
  has_one_attached :e_imageseiko22
  has_one_attached :e_imageseiko23
  has_one_attached :e_imageseiko24
  has_one_attached :e_imageseiko25
  has_one_attached :e_imagesippai1
  has_one_attached :e_imagesippai2
  has_one_attached :e_imagesippai3
  has_one_attached :e_imagesippai4
  has_one_attached :e_imagesippai5
  has_one_attached :e_imagesippai6
  has_one_attached :e_imagesippai7
  has_one_attached :e_imagesippai8
  has_one_attached :e_imagesippai9
  has_one_attached :e_imagesippai10
  has_one_attached :e_imagesippai11
  has_one_attached :e_imagesippai12
  has_one_attached :e_imagesippai13
  has_one_attached :e_imagesippai14
  has_one_attached :e_imagesippai15
  has_one_attached :e_imagesippai16
  has_one_attached :e_imagesippai17
  has_one_attached :e_imagesippai18
  has_one_attached :e_imagesippai19
  has_one_attached :e_imagesippai20
  has_one_attached :e_imagesippai21
  has_one_attached :e_imagesippai22
  has_one_attached :e_imagesippai23
  has_one_attached :e_imagesippai24
  has_one_attached :e_imagesippai25

end